GET http://localhost:3000/ HTTP/1.1
content-type: application/json

###

POST http://localhost:3001/user HTTP/1.1
content-type: application/json

{
    "firstName":123,
    "lastName": 123
}

###
PATCH http://localhost:3001/user/c5008b48-57c4-45ef-be1a-ad89fdb13152 HTTP/1.1
content-type: application/json

{
    "firstName": "you",
    "lastName": "you"
}

###

GET http://localhost:3001/user/c5008b48-57c4-45ef-be1a-ad89fdb13152 HTTP/1.1
content-type: application/json
###

GET http://localhost:3001/user HTTP/1.1
content-type: application/json
###

DELETE  http://localhost:3001/user/c5008b48-57c4-45ef-be1a-ad89fdb13152 HTTP/1.1
content-type: application/json
