GET http://localhost:3000/ HTTP/1.1
content-type: application/json

###

POST http://localhost:3001/v1/user HTTP/1.1
content-type: application/json

{
    "firstName": "test",
    "lastName": "test1"
}

###
PATCH http://localhost:3000/user/376536ec-13bb-4a4b-81a8-f052834e1f1f HTTP/1.1
content-type: application/json

{
    "firstName": "update",
    "lastName": "update"
}

###

GET http://localhost:3001/v1/user/44ae254f-0f89-402b-92c2-416746f87ef1 HTTP/1.1
content-type: application/json
###

GET http://localhost:3001/v1/user HTTP/1.1
content-type: application/json
###

DELETE  http://localhost:3001/v1/user/d0813298-695c-46f7-8611-2d7c8560c959 HTTP/1.1
content-type: application/json
